theme: minima

title: "Anthony McWhite"
description: "Data, systems, applied technology, and field research"
author: "Anthony McWhite"

# If my repo is "my-name".github.io, baseurl (below) should be empty. Nothing in -->  "".
baseurl: ""
url: "https://anthonymcwhite.github.io"

minima:
  skin: dark

header_pages:
  - about.md
  - projects.md
  - writing.md
  - credentials.md
  - contact.md

plugins:
  - jekyll-feed
